### ISSUE TITLE
Request for Multi-GPU training support

### ISSUE THREAD

**Issue by meetps** [DeNA/Chainer_Mask_R-CNN#1]
Thanks a lot for your code!

I'd like to send in a PR for multi-GPU support. What would be a good place for me to start? Is there a way in which one can use data parallelism with the existing subdivisionUpdater?

**Comment by hirotomusiker** [comment]
Thank you for your comment! 
The simplest way would be changing
https://github.com/DeNA/Chainer_Mask_R-CNN/blob/master/train.py#L116
to:
`
updater = training.ParallelUpdater(
        train_iter,  optimizer,
          devices={'main': args.gpu0, 'second': args.gpu1},
    )
`
instead of using the SubdivisionUpdater.  

See:
https://github.com/chainer/chainer/blob/master/examples/mnist/train_mnist_data_parallel.py

**Comment by meetps** [comment]
I tried that, but it gives an error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 342, in update_core
    batch[i::n], self._devices[key])
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 93, in concat_examples
    [example[i] for example in batch], padding[i])))
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 123, in _concat_arrays
    return xp.concatenate([array[None] for array in arrays])
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train_voc.py", line 159, in main
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 342, in update_core
    batch[i::n], self._devices[key])
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 93, in concat_examples
    [example[i] for example in batch], padding[i])))
  File "/usr/local/lib/python2.7/dist-packages/chainer/dataset/convert.py", line 123, in _concat_arrays
    return xp.concatenate([array[None] for array in arrays])
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

Maybe I have to overload the `update_core` method of ParallelUpdater ?

**Comment by hirotomusiker** [comment]
I have reproduced the same error only when the batchsize in
` train_iter = chainer.iterators.SerialIterator(
        train_data, batch_size=args.batchsize)`
is different from the number of devices :
`updater = training.ParallelUpdater( train_iter, optimizer, devices={'main': args.gpu0, 'second': args.gpu1}, )`
Could you check that?

**Comment by meetps** [comment]
Yes, the issue is only when batchsize is not equal to number of devices. 

However, with the default configuration can fit a batchsize of `7` on a Titan X, would be great to use a batchsize of `7N` on an `N` GPU system.

**Comment by hirotomusiker** [comment]
OK then the issue is that training with batchsize>1 is not supported currently.
Please give me some time to modify the trainer.

**Comment by hirotomusiker** [comment]
Just updated train.py and added mask_rcnn_train_chain_batch.py.
Please import mask_rcnn_train_chain_batch instead of mask_rcnn_train_chain when enabling minibatch mode, and use ParallelUpdater for multiple GPUs.
args.batchsize % (number of devices) should be zero.
Hope it works out...
